### ISSUE TITLE
New Applet: Das Ping

### ISSUE THREAD

**Issue by soluml** [DasKeyboard/q-marketplace#11]
**A different spin on a ping app!**

https://github.com/soluml/daskeyboard-applet--dasping

Das Ping Leverages the DasKeyboard's interval and intelligently determines the color gradient. No 3rd party dependencies and super easy to configure!

**Comment by Mubramaj** [comment]
Hi @soluml ,
Thank you for your contribution. Your applet will be reviewed and added to the Marketplace. I will notify you here when the applet will be public.

**Comment by Mubramaj** [comment]
Hi @soluml, 
I created a new pull request to your repo to remove the image tags from the README due to the markdown interpretor of the Das Keyboard Application that has an issue with the <img> tag.

Can you also please add some tests. You can use a framework like mocha for example. There is example of tests in every daskeyboard applet in the marketplace.

Thank you,
Ahmed

**Comment by soluml** [comment]
Hello!

I've merged the PR. Will also look into adding a few Mocha tests.

**Comment by Mubramaj** [comment]
Awesome news. Let me know here when it's done.

**Comment by soluml** [comment]
Alright, tests added.  Should be good to go!

**Comment by soluml** [comment]
@Mubramaj any updates?

**Comment by Mubramaj** [comment]
Hi @soluml, 
Your applet have been added to the Das Keyboard Q Marketplace.
Thank you for your contribution

Best,
Ahmed
